import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    background: #313E50;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }

        Row {
            LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Enter your number";
                height: 35px;
            }
        }

        Row {
            Button {
                text: "calculate";
                primary: true;
                height: 35px;
            }
        }
    }
}
