import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {

    in property <string> results: "";
    in-out property <bool> opencurtain;
    callback divide-income(string);



    background: #313E50;
    
    
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }

        Row {
            income := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Enter your number";
                height: 35px;
            }
        }

        Row {
            Button {
                text: "calculate";
                primary: true;
                height: 35px;
                clicked => {
                    root.opencurtain = !root.opencurtain;
                    divide-income(income.text);
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #F2F2F2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }

                    Rectangle {
                        background: #333333;
                        x:0px;
                        width: opencurtain ? 0px : parent.width / 2;
                        height: parent.height;
                        animate width {
                             duration: 250ms;
                             easing: ease-in;
                        }
                    }

                    Rectangle {
                        background: #333333;
                        x: opencurtain ? parent.width : parent.width / 2;
                        width: opencurtain ? 0px : parent.width / 2;
                        height: parent.height;
                        animate width {
                             duration: 250ms;
                             easing: ease-in;
                        }
                        animate x {
                             duration: 250ms;
                             easing: ease-in;
                        }
                    }
    
                }

                
               
            }
        }
    }
}
